server:
  port: 5005  # Port du gateway

spring:
  cloud:
    gateway:
      routes:
        - id: patientApi
          uri: http://localhost:5000    # Port de patient-api
          predicates:
            - Path=/api/patients/** 
        - id: noteApi
          uri: http://localhost:5002    # Port de patient-api
          predicates:
            - Path=/api/notes/** 
